# Resolve react_native_pods.rb with node to allow for hoisting
require_relative '../node_modules/react-native/scripts/react_native_pods'
platform :ios, min_ios_version_supported
prepare_react_native_project!
$RCTNewArchEnabled = ENV['RCT_NEW_ARCH_ENABLED'] == '1'
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
linkage = ENV['USE_FRAMEWORKS']

target 'unifi' do
  use_expo_modules!   
  config = use_native_modules!   
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true, 
    :fabric_enabled => $RCTNewArchEnabled,
    :new_arch_enabled => $RCTNewArchEnabled  
  )
  # permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  # pod 'react-native-permissions', :path => "#{permissions_path}/Camera.podspec"
  post_install do |installer|
    react_native_post_install(
      installer,
      File.join(__dir__, '../node_modules/react-native'),
      # :mac_catalyst_enabled => false,
      # :hermes_enabled => true,
      # :fabric_enabled => $RCTNewArchEnabled
    )
    installer.pods_project.targets.each do |target|
      if target.name == 'React-RCTFabric'
        target.build_configurations.each do |config|
          config.build_settings['OTHER_LDFLAGS'] = '-ld64'
        end
      end
    end
  end
end
